add missing python library files for rdkit error
ImportError: libboost_python-py27.so.1.62.0: cannot open shared object file: No such file or directory